dist: xenial
language: ruby
cache:
  bundler: true
  directories:
    - vendor/bundle
    - node_modules
    - /home/travis/.rvm/
    - /home/.cache/yarn

services:
  - postgresql

before_install:
  - sudo apt-get install -y chromium-chromedriver=73.0.3683.103

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

script:
  - bin/ci-build
