dist: xenial
language: ruby
cache:
  directories:
    - vendor/bundle
    - node_modules
    - /home/travis/.rvm/
    - /home/.cache/yarn

env:
  - RAILS_ENV=test

script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rails db:setup
 — bundle exec rails db:migrate
 — bundle exec rails test
addons:
  postgresql: "11"
  chrome: stable

services:
  - postgresql
  - redis-server
