dist: xenial
language: ruby
cache:
  directories:
    - vendor/bundle
    - node_modules
    - /home/travis/.rvm/
    - /home/.cache/yarn
addons:
  postgresql: "11.3"
  chrome: stable
services:
  - postgresql
script:
  - bin/ci-build
