dist: xenial
language: ruby
cache:
  bundler: true
  directories:
    - vendor/bundle
    - node_modules
    - /home/travis/.rvm/
    - /home/.cache/yarn

services:
  - postgresql

addons:
  apt:
    packages:
      - google-chrome-stable
      - chromium-chromedriver-73

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

script:
  - bin/ci-build
